"""third migration

Revision ID: bf2b6547c5e0
Revises: 04fdee6405ca
Create Date: 2018-04-19 16:25:21.309716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf2b6547c5e0'
down_revision = '04fdee6405ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('albumid', sa.Integer(), nullable=True))
    op.add_column('songs', sa.Column('genre', sa.String(length=64), nullable=True))
    op.create_foreign_key(None, 'songs', 'albums', ['albumid'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'songs', type_='foreignkey')
    op.drop_column('songs', 'genre')
    op.drop_column('songs', 'albumid')
    # ### end Alembic commands ###
