"""fourth migration

Revision ID: e68348ad6a48
Revises: bf2b6547c5e0
Create Date: 2018-04-19 16:46:34.485963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e68348ad6a48'
down_revision = 'bf2b6547c5e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('avatar', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(length=100), nullable=True))
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.drop_column('users', 'username')
    op.drop_column('users', 'profilepic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profilepic', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.drop_column('users', 'name')
    op.drop_column('users', 'avatar')
    op.drop_column('users', 'active')
    # ### end Alembic commands ###
